server:
 port: 8080

spring:
 datasource:
  url: jdbc:mysql://localhost:3306/department_db?useSSL=false&serverTimezone=UTC
  username: root
  password: 123456
 jpa: 
  open-in-view: false
  hibernate:
   ddl-auto: update
 boot: 
  message: Hello, Department Service Spring Cloud Bus

eureka:
 instance:
  client:
   serverUrl:
    defaultZone: http://localhost:8761/eureka/
