server:
 port: 8081
 
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/employee_db?useSSL=false&serverTimezone=UTC
  username: root
  password: 123456
 jpa: 
  open-in-view: false
  hibernate:
   ddl-auto: update
   
eureka:
 instance:
  client:
   serverUrl:
    defaultZone: http://localhost:8761/eureka/
